site_name: 服务器编程新手入门 - Server Programming Guide
site_url: https://liuhaohua.com/server-programming-guide/
repo_url: https://github.com/howardlau1999/server-programming-guide/
copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
extra:
  analytics:
    provider: google
    property: G-C7E0KYN4VG
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  language: zh
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 白天模式
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Shanghai
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css

nav:
  - 概览: "index.md"
  - 编译链接基础知识:
    - 概览: "basics/index.md"
    - 编译过程概览: "basics/procedure.md"
    - 静态链接与动态链接: "basics/static-dynamic-linkage.md"
    - 程序的装载与运行: "basics/loading.md"
    - 扩展知识：利用链接与加载覆盖程序函数: "basics/hooks.md"
    - 扩展知识：交叉编译: "basics/cross-compilation.md"
  - 构建系统:
    - 概览: "build-system/index.md"
    - Make: "build-system/make.md"
    - Ninja: "build-system/ninja.md"
    - Bazel: "build-system/bazel.md"
    - XMake: "build-system/xmake.md"
    - 编译缓存: "build-system/build-cache.md"
    - 分布式编译: "build-system/distributed-compiling.md"
  - 元构建系统:
    - 概览: "meta-build-system/index.md"
    - Autotools: "meta-build-system/autotools.md"
    - CMake: "meta-build-system/cmake.md"
    - GN: "meta-build-system/gn.md"
    - 在项目中使用第三方库: "meta-build-system/third-party-library.md"
  - 代码生成:
    - 概览: "codegen/index.md"
  - 编写测试:
    - 概览: "testing/index.md"
    - "使用 diff 进行测试": "testing/diff.md"
    - "使用 Google Test 进行测试": "testing/googletest.md"
  - 代码静态分析:
    - 概览: "static-analysis/index.md"
    - 代码格式化: "static-analysis/format.md"
    - 静态检查: "static-analysis/lint.md"
  - 持续集成:
    - 概览: "ci/index.md"
    - "使用 Github Actions 进行持续集成": "ci/github-actions.md"
  - 日志系统:
    - 概览: "logging/index.md"
    - 结构化日志: "logging/structured-logging.md"
    - 二进制日志: "logging/binary-logging.md"
    - "使用 Boost.Log": "logging/boost.md"
  - 指标系统:
    - 概览: "metrics/index.md"
    - "使用 Prometheus 指标库": "metrics/prometheus.md"
  - 调试工具:
    - 概览: "debugging/index.md"
    - "gdb 调试工具": "debugging/gdb.md"
    - "配置 VS Code 调试": "debugging/vscode.md"
    - "调试内存转储文件": "debugging/coredump.md"
  - 内存管理:
    - 概览: "memory/index.md"
    - 智能指针: "memory/smart-pointer.md"
    - "AddressSanitizer 内存安全检测": "memory/address-sanitizer.md"
    - "Valgrind 内存安全检测": "memory/valgrind.md"
    - 内存池: "memory/memory-pool.md"
  - 进入并行编程世界:
    - 多线程编程: "parallel/multi-threading.md"
    - 多进程编程: "parallel/multi-processing.md"
    - 实战:
      - 多线程共享队列: "parallel/practice/multi-threading-queue.md"
      - 多进程共享队列: "parallel/practice/multi-processing-queue.md"
      - 回调模型: "parallel/practice/callback.md"
      - "Future 模型": "parallel/practice/future.md"
      - 取消操作: "parallel/practice/cancellation.md"
      - 操作超时: "parallel/practice/timeout.md"
      - 线程池: "parallel/practice/thread-pool.md"
      - 进程池: "parallel/practice/process-pool.md"
  - 网络编程 RPC 入门:
    - 概览: "rpc/index.md"
    - 序列化与反序列化: "rpc/serialization.md"
    - "使用 RPC 框架": "rpc/framework.md"
    - 编写服务端: "rpc/server.md"
    - 编写客户端: "rpc/client.md"
  - 存储系统:
    - 概览: "storage/index.md"
    - 存储模型:
      - "键值对 KV 存储": "storage/kv.md"
      - 关系型数据库: "storage/rdbms.md"
      - 对象存储: "storage/object-storage.md"
      - 其他存储模型: "storage/custom.md"
    - 存储位置:
      - 本地存储: "storage/local.md"
      - 远程存储: "storage/remote.md"
      - 分布式存储: "storage/distributed.md" 
  - 服务器程序常见范式:
    - 系统设计范式: "paradigms/system-design.md"
    - 编程范式:
      - 概览: "paradigms/index.md"
      - 程序的运行配置: "paradigms/config.md"
      - 控制反转: "paradigms/ioc.md"
      - 注册请求处理器: "paradigms/handlers.md"
      - 启动后台服务: "paradigms/background.md"
      - 创建监听端口监听请求: "paradigms/listen.md"
      - 插件: "paradigms/plugin.md"
  - 编写文档:
    - 概览: "documentation/index.md"
  - 部署上线: 
    - 概览: "deployment/index.md"
    - 程序的打包: "deployment/packaging.md"
    - 反向代理: "deployment/reverse-proxy.md"
    - "systemd 部署": "deployment/systemd.md"
    - "Docker 部署": "deployment/docker.md"
  - 与他人合作:
    - 快速上手项目: "collaboration/getting-started-on-a-project.md"
    - "实际的 Git 场景":
      - 概览: "collaboration/git-workflow/index.md"
      - 解决代码合并冲突: "collaboration/git-workflow/resolve-conflicts.md"
      - 高效地处理分支切换: "collaboration/git-workflow/switching-branches.md"
      - "fork 与多远端仓库下的协作": "collaboration/git-workflow/fork-and-multi-remote-repositories.md"
  - 附录:
    - 配置基本编程环境: "appendix/build-env.md"
  